### ISSUE TITLE
Using oneOf/anyOf without careful consideration can be a performance killer

### ISSUE THREAD

**Issue by unguul** [json-schema-org/community#520]
As per https://github.com/justinrainbow/json-schema/issues/640, having multiple `oneOf` entries can severely impact performance, especially when validating nested data.

While this might be an implementation specific problem, it might be worth adding some sort of warning in the docs to make people aware of this caveat.

**Comment by benjagm** [comment]
Closed as per : https://github.com/json-schema-org/understanding-json-schema/pull/131

**Comment by gregsdennis** [comment]
@benjagm why was this closed?  The PR was closed because it's the wrong repo now, but this issue should remain open as it hasn't been addressed.

**Comment by benjagm** [comment]
> why was this closed?

Yesterday did a round of issues review and my perception when reading this issue was that https://github.com/json-schema-org/understanding-json-schema/pull/131 added this warning in the docs :

**Careful consideration should be taken when using multiple `oneOf` entries with nested data structures as the number of validation checks performed will increase exponentially resulting in poor performance.**

However I just realized that that PR was not merged. Is if ok to reopen this and send a PR with that change in our docs?

If not, what is the pending discussion/action?

**Comment by unguul** [comment]
@benjagm I think @gregsdennis got it right, the PR I made was open for such a long time that the docs moved. As far as I'm concerned, a warning in the docs as you mentioned is fine. I'm happy to open another PR against the right place if that's wanted.

**Comment by unguul** [comment]
https://github.com/json-schema-org/website/pull/323

**Comment by benjagm** [comment]
Closed as completed with https://github.com/json-schema-org/website/pull/323
