### ISSUE TITLE
Provide clear explanations on what all 13 repos are for and their state

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/community#80]
We should make it clear what each repo is and the state of said repo.
https://www.repostatus.org provides an approach which seems reasonable.

**Comment by Relequestual** [comment]
9 of the repos now have a "repo status" badge.
1 repo now has a [PR](https://github.com/json-schema-org/json-hyperschema-spec/pull/15) which will add a "repo status" badge.

**Comment by Relequestual** [comment]
https://project-types.github.io/ also maybe useful

**Comment by Julian** [comment]
Scribbling some additional notes in this comment (which I'll edit):

- [x] Added a link to the blog directly to the sidebar of [its repo](https://github.com/json-schema-org/blog)
- [x] Added some trivial GitHub tags to the blog repo

**Comment by Julian** [comment]
The two links (repostatus and project-types) seem fundamentally very similar to me personally, so I don't see a huge difference in using one or the other -- I think since we've used one so far we may as well finish off with that one and then can later decide if we like the other for whatever reason, to move everything to that.

More holistically though, [to me, as I mentioned here](https://github.com/json-schema-org/json-hyperschema-spec/pull/15#issuecomment-1159110122) it's not 100% clear a badge is "loud enough" sometimes. I put something in the sidebar there, which maybe along with the badge is a good enough signal, so perhaps I'll put that forward concretely -- that repositories which are particularly in-progress or POC should additionally mention that in their sidebar. Hopefully folks agree?

(Looking into the rest of the repos now)
